<?php $escape = $this->plugin('escapeHtml');?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item resource browse');
$query = $this->params()->fromQuery(); ?>
<?php if (isset($itemSet)): ?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id(); ?>
<?php endif; ?>

<?php if (isset($itemSet)): ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
    <div class="metadata">
        <?php echo $itemSet->displayValues(); ?>
    </div>
    <?php echo $this->pageTitle($this->translate('Items'), 3); ?>
<?php else: ?>
    <?php echo $this->pageTitle($this->translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>
<?php echo $this->hyperlink($this->translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
<?php echo $this->pagination(); ?>
<ul class="resource-list">
    <?php foreach ($items as $item): ?>
    <li class="item resource">
        <?php if ($primaryMedia = $item->primaryMedia()): ?>
        <?php echo $item->linkRaw($this->thumbnail($primaryMedia, 'medium')); ?>
        <?php endif; ?>
        <h4><?php echo $item->link($item->displayTitle()); ?></h4>
        <?php if ($item->value('collection:primaryCollection') || $item->value('collection:secondaryCollection')): ?>
        <div class="collection-info">
        <?php if ($primaryCollection = $item->value('collection:primaryCollection')): ?>
        <span class="collection-primary"><?php echo $primaryCollection; ?></span>
        <?php endif; ?>
        <?php if ($secondaryCollection = $item->value('collection:secondaryCollection', ['all' => false]) && $item->value('collection:primaryCollection')): ?>
        <span class="collection-secondary"> > <?php echo $secondaryCollection; ?></span>
        <?php else: ?>
        <span class="collection-secondary"><?php echo $secondaryCollection; ?></span>
        <?php endif; ?>
        </div>
        <?php endif; ?>
        <?php if ($description = $item->value('dcterms:description')): ?>
        <div class="description"><?php echo mb_strimwidth($description,0,120,'[...]'); ?></div>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php echo $this->pagination(); ?>
<?php $this->trigger('view.browse.after'); ?>
