<?php 
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$this->headScript()->prependFile($this->assetUrl('js/lightslider.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/lightgallery.min.js'));
$this->headLink()->prependStylesheet($this->assetUrl('css/lightgallery.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/lightslider.min.css'));
$lightMedia = [];
$otherMedia = [];
foreach ($item->media() as $media) {
    $mediaType = $media->mediaType(); 
    $mediaRenderer = $media->renderer(); 
    if ((strpos($mediaType, 'image') !== false) || (strpos($mediaRenderer, 'youtube') !== false)) {
        $lightMedia[] = $media; 
    } else {
        $otherMedia[] = $media; 
    }
}
?>

<?php echo $this->pageTitle($item->displayTitle() . ' (' . $this->translate($item->displayResourceClassLabel()) .')' , 2); ?>
<?php if (count($lightMedia) > 0): ?>
<ul id="itemfiles" class="media-list">
    <?php foreach ($lightMedia as $media): ?>
        <?php $source = ($media->originalUrl()) ? $media->originalUrl() : $media->source(); ?>
        <li data-src="<?php echo $source; ?>" data-thumb="<?php echo $escape($media->thumbnailUrl('medium')); ?>" class="media resource">
            <?php echo $media->render(); ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<?php if ($item->value('collection:primaryCollection') || $item->value('collection:secondaryCollection')): ?>
        <div class="collection-info">
        <?php if ($primaryCollection = $item->value('collection:primaryCollection')): ?>
        <span class="collection-primary"><?php echo $primaryCollection; ?></span>
        <?php endif; ?>
        <?php if ($secondaryCollection = $item->value('collection:secondaryCollection', ['all' => false])): ?>
        <span class="collection-secondary"><?php echo $secondaryCollection; ?></span>
        <?php endif; ?>
        </div>
<?php endif; ?>


<div class="item-information">
<?php if ($description = $item->value('dcterms:description')): ?>
<div class="property dcterms-description">
  <div class="values">
    <div class="value"><?php echo $description; ?></div>
  </div>
</div>
<?php endif; ?>

<?php if ($creator = $item->value('dcterms:creator')): ?>
<div class="property dcterms-creator">
  <div class="values">
    <div class="value"><?php echo $creator; ?></div>
  </div>
</div>
<?php endif; ?>

<?php if ($created = $item->value('dcterms:created')): ?>
<div class="property dcterms-created">
  <div class="values">
    <div class="value"><?php echo $created; ?></div>
  </div>
</div>
<?php endif; ?>

<?php if ($places= $item->value('dcterms:spatial', ['all'=>true])): ?>
<div class="property dcterms-spatial">
  <div class="values">
    <?php foreach ($places as $place): ?>
    <div class="value"><?php echo $place; ?></div>
  <?php endforeach;?>
  </div>
</div>
<?php endif; ?>

</div>

<?php echo $item->displayValues(); ?>



<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<div id="item-linked">
    <h3><?php echo $this->translate('Linked resources'); ?></h3>
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>


<?php


$embedMedia = $this->siteSetting('item_media_embed', false);
/* @var $itemMedia Omeka\Api\Representation\MediaRepresentation[] */
$itemMedia = $item->media();

if ($embedMedia && $itemMedia)
  foreach ($itemMedia as $medium)
    if(stristr($medium->displayTitle(), 'transcription')) {
      echo $medium->render();
      break;
    }



 ?>


<?php $this->trigger('view.show.after'); ?>

<script src="<?php echo $this->assetUrl('js/lg-video.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->assetUrl('js/lg-zoom.js'); ?>" type="text/javascript"></script>

<script>
    jQuery(document).ready(function() {
      $('#itemfiles').lightSlider({
          mode: 'fade',
          autoWidth: true,
          adaptiveHeight:false,
          gallery:true,
          item:1,
          loop:true,
          thumbItem:15,
          slideMargin:0,
          enableDrag: false,
          currentPagerPosition:'middle',
          onSliderLoad: function(el) {
              el.lightGallery({
                  selector: '#itemfiles .media',
                  download: false,
                  zoom: true,
                  youtubePlayerParams: {
                      modestbranding: 1,
                      showinfo: 0,
                      rel: 0,
                      controls: 1
                  },
                  vimeoPlayerParams: {
                      byline : 0,
                      portrait : 0,
                      color : 'A90707'     
                  },
              });
          }   
      });  
    });
</script>
