<div class="preview-block">

<?php if ($this->heading): ?>
<h2><?php echo $this->heading; ?></h2>
<?php endif; ?>

<ul class="resource-list">
    <?php foreach ($items as $item): ?>
    <li class="item resource">
        <?php if ($primaryMedia = $item->primaryMedia()): ?>
        <?php echo $item->linkRaw($this->thumbnail($primaryMedia, 'medium')); ?>
        <?php endif; ?>
        <h4><?php echo $item->link($item->displayTitle()); ?></h4>
        <?php if ($item->value('collection:primaryCollection') || $item->value('collection:secondaryCollection')): ?>
        <div class="collection-info">
        <?php if ($primaryCollection = $item->value('collection:primaryCollection')): ?>
        <span class="collection-primary"><?php echo $primaryCollection; ?></span>
        <?php endif; ?>
        <?php if ($secondaryCollection = $item->value('collection:secondaryCollection', ['all' => false]) && $item->value('collection:primaryCollection')): ?>
        <span class="collection-secondary"> > <?php echo $secondaryCollection; ?></span>
        <?php else: ?>
        <span class="collection-secondary"><?php echo $secondaryCollection; ?></span>
        <?php endif; ?>
        </div>
        <?php endif; ?>
        <?php if ($description = $item->value('dcterms:description')): ?>
        <div class="description"><?php echo mb_strimwidth($description,0,120,'[...]'); ?></div>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>

<?php
$linkText = $this->linkText == '' ? $this->translate('Browse all') : $this->linkText;
echo $this->hyperlink($linkText, $this->url(
    'site/resource', ['controller' => 'item', 'action' => 'browse'], ['query' => $this->query], true
));
?>

</div>